Lesson 6.1
htmlacademy-ecmascript/631113-big-trip-16 pull request #10
Opened 2022-01-21 08:41 UTC by 1ak0t

2022-01-21 10:21 UTC, AlexMasterov requested changes

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150507464-e47b3cc0-7f34-4d7b-97e3-07f2c569f4e6.png)
![image](https://user-images.githubusercontent.com/700213/150507515-8b7cac2b-abdc-4af4-8796-88e19cbf77fb.png)

</details>

Если в форму редактирования точки маршрута внести изменения, например цены, и не сохранить нажатием на кнопку `Save`, то после закрытия формы цена в форме не сбрасывается.

См. ТЗ:
> Кнопка «Save». Сохраняет изменения, закрывает форму редактирования

> Если пользователь внёс изменения в точку маршрута, не выполнил сохранение и пытается перейти к редактированию другой точки маршрута либо создать новую, то **в этом случае открытая форма редактирования скрывается без сохранения изменений**

> При нажатии кнопки «Esc» или кнопки с изображением «Стрелка вверх» в правом углу форма редактирования закрывается. **Несохранённые изменения пропадают**

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
<details>
<summary>Проблема</summary>

```
point-presenter.js:31 Uncaught TypeError: offers is not iterable
```
</details>

При добавление точки маршрута в избранное выбрасывается исключение (ошибка).

Б2

Нужно исправить.

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150508092-5655dbe1-a4af-49e8-ad23-305bb1fc31fc.png)
![image](https://user-images.githubusercontent.com/700213/150508140-4685da78-aaf0-4410-b4c3-5eb70be373b6.png)


</details>

Выбранные в форме доп. опции после сохранения не отображаются в точке маршрута из списка.

Нужно доработать.

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
Изменение стоимости в форме не отображаются в точке маршрута из списка.

Нужно доработать.

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
```
edit-create-point-view.js:154 Uncaught TypeError: Cannot set properties of undefined (setting 'length')
```
При изменение названия направления в форме выбрасывается исключение (ошибка).

Нужно исправить.

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150508609-e0d15719-b3ce-47e3-bb9a-820f36974b65.png)

</details>

Сейчас форма позволяет ввести и сохранить свое название направления.

См. ТЗ:
> Пункт назначения. Выбирается из списка предложенных значений, полученных с сервера. **Пользователь не может ввести свой вариант для пункта назначения**

На свое усмотрение нужно реализовать валидацию или запретить ввод.

> В итоге пользователь не должен иметь возможность вводить или сохранять форму с невалидными значениями

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150509222-b9cd80ae-6c94-4aaa-a73c-a8ea4d1ae721.png)

</details>

Сейчас можно сохранить форму с отрицательной стоимость.

См. ТЗ:
> Стоимость. **Целое положительное число**

Нужно доработать.

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150510425-d6fb534a-c8e7-4222-a30e-9be62d8620b9.png)

```
Uncaught TypeError: Cannot set properties of undefined (setting 'length')
```
</details>

В форме при изменение типа точки маршрута выбрасывается исключение (ошибка).

Нужно исправить.

> \+ Изменения точки маршрута должны соответствовать ожиданию ТЗ

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150509981-0fb73ab2-ebc5-47f3-a5f2-d20c77b5bfe4.png)

https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/d1cb726cb9361d3bd31f1f4c012f3f9466d8b728/src/view/top-route-info-view.js#L8-L11
</details>

Повторю, что общая стоимость путешествия должна также учитывать стоимость выбранных опций.

2022-01-21 10:21 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
```
edit-create-point-view.js:154 Uncaught TypeError: Cannot set properties of undefined (setting 'length')
```
Если попробовать закрыть форму редактирования точки маршрута по `Esc`, то снова эта ошибка 😟

Нужно исправить.

2022-01-22 05:16 UTC, 1ak0t commented on src/view/edit-create-point-view.js
> +export default class EditCreatePointView extends SmartView{
Здесь не понял. 
`export default class EditCreatePointView extends SmartView{
  #choosedOffers = [];
  #offers = [];
  #destinations = [];
//1. Конструктор
  constructor(point, offers, destinations) {
    super();
    this._data = EditCreatePointView.parsePointToData(point);
    this.#offers = offers;
    this.#destinations = destinations;
    this.#setInnerHandlers();
  }
//2. Геттеры и сеттеры
  get template() {
    return createEventEditTemplate(this._data, this.#destinations);
  }
//3.1 Методы класса
  reset = (point) => {
    this.updateData(EditCreatePointView.parsePointToData(point));
  }

  resetData = () => {
    if (this._data.length > 0) {
      this._data.choosedOffers.length = 0;
    }
  }

  restoreHandlers = () => {
    this.#setInnerHandlers();
    this.setCloseClickHandler(this._callback.closeClick);
    this.setSubmitFormHandler(this._callback.submitClick);
  }

  setCloseClickHandler = (callback) => {
    this._callback.closeClick = callback;
    this.element.querySelector('.event__rollup-btn').addEventListener('click', this.#closeButtonClickHandler);
  }

  setSubmitFormHandler = (callback) => {
    this._callback.submitClick = callback;
    this.element.querySelector('form').addEventListener('submit', this.#formSubmitHandler);
  }
//3.2 Приватные методы
  #getOffersList = (offers, type) => offers.filter((offer) => offer['type'] === type)[0].offers;

  #getDestination = (destinations, destinationName) => (destinations.filter((destination) => destination.name === destinationName)[0]);

  #setInnerHandlers = () => {
    this.#setTypeInputHandler();
    this.#setDestinationInputHandler();
    this.#setChooseOfferHandler();
  }

  #setTypeInputHandler = () => {
    const typeInput = this.element.querySelectorAll('.event__type-input');
    typeInput.forEach((input) => input.addEventListener('input', this.#typeInputChangeHandler));
  }

  #setDestinationInputHandler =() => {
    this.element.querySelector('.event__input--destination').addEventListener('change', this.#destinationInputChangeHandler);
  }

  #setChooseOfferHandler = () => {
    const offerButtons = this.element.querySelectorAll('.event__offer-checkbox');
    if (offerButtons.length > 0) {
      offerButtons.forEach((button) => button.addEventListener('click', this.#offerCheckboxClickHandler));
    }
  }
//4 Обработчики
  #typeInputChangeHandler = (evt) => {
    this.updateData({
      type: evt.target.value,
      offers: this.#getOffersList(this.#offers, evt.target.value),
    });
  }

  #destinationInputChangeHandler = (evt) => {
    this.updateData({
      destination: this.#getDestination(this.#destinations, evt.target.value),
    });
  }

  #offerCheckboxClickHandler = (evt) => {
    const button = evt.target.dataset.id;
    const offerId = Number(button);
    if (this.#choosedOffers.length > 0 && this.#choosedOffers.includes(offerId)) {
      this.#choosedOffers.splice(this.#choosedOffers.indexOf(offerId),1);
      this._data = {...this._data, choosedOffers: this.#choosedOffers};
      return;
    }
    this.#choosedOffers.push(offerId);
    this._data = {...this._data, choosedOffers: this.#choosedOffers};
  }

  #closeButtonClickHandler = () => {
    this._callback.closeClick();
  }

  #formSubmitHandler = (evt) => {
    evt.preventDefault();
    this._callback.submitClick(EditCreatePointView.parseDataToPoint(this._data));
  }
//5. Статические методы
  static parsePointToData = (point) => ({...point})

  static  parseDataToPoint = (data) => {
    const point = {...data};
    return point;
  }
}`

2022-01-22 05:25 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
> +export default class EditCreatePointView extends SmartView{
На защите проекта в "геттеры и сеттеры" (2) также включают обычные методы, название которых начинается с `get*` или `set*`.

Например:
`setTypeInputHandler`
`setDestinationInputHandler`
и т.п.

2022-01-22 05:30 UTC, AlexMasterov commented on src/view/smart-view.js
> +    const newElement = this.element;
> Сами нарушают

См. критерий:
> если есть переменные, которые хранят DOM-элемент и содержат слово `Element`, **то это правило работает везде**

В проекте демо суффикс `Element` используется для _всех_ переменных, которые содержат DOM-элементы (= `instanceof Element`). У тебя же только здесь.

> Так как ты предлагаешь - не получиться. New нельзя использовать в качестве названия переменной

В замечание предлагает переименовать без `Element`, а не просто убрать его из названия. Например, назвать что-то вроде `prevNode` и т.п.

2022-01-22 05:34 UTC, 1ak0t commented on src/view/edit-create-point-view.js
> +export default class EditCreatePointView extends SmartView{
Тут получается я могу поднять в позицию после get только setCloseClickHandler и setSubmitFormHandler. 
setTypeInputHandler, setDestinationInputHandler - это же уже приватные методы.
Так?)

2022-01-22 05:47 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
> +export default class EditCreatePointView extends SmartView{
Ну да.
Еще можно дождаться проверки случайным проверяющим, а с ним как повезет 😃).

> это же уже приватные методы

См. критерий:
> Сортировка основных методов объекта свободная, подразумевается что методы будут расположены оптимально для конкретного класса

По критерию "приватные методы" можно поднять выше "методов класса" и "перегруженных". Тогда в случае этого класса такие методы окажутся сразу после "геттеров и сетторов" (2). Тогда всем угодишь 😃

> В других языках обычно любой метод с названием `get` или `set` называют геттером и сеттером

2022-01-22 05:53 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
> +export default class EditCreatePointView extends SmartView{
Если хочешь, то можем уточнить этот критерий у самих авторов курса. Возможно что-то изменилось.

2022-01-22 06:12 UTC, 1ak0t commented on src/view/edit-create-point-view.js
Если я правильно понял задание, то пока не стоит задачи при сохранении формы перерисовывать точку маршрута и общую стоимость путешествия.

2022-01-22 06:47 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
> и _общую_ стоимость путешествия

В моем замечание нет такого требования.

Это _необязательное_ доп. пункт ТЗ, который лучше доработать в задание, где потребуется добавить модель. (у модели будет возможность подписаться на обновление данных, что поможет упростить обновление)

2022-01-22 06:48 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
> Если я правильно понял задание, то пока не стоит задачи при сохранении формы перерисовывать точку маршрута

https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/d1cb726cb9361d3bd31f1f4c012f3f9466d8b728/src/presenter/points-list-presenter.js#L90-L93

Это было реализовано в задание прошлого модуля, а в этом должно работать с учетом использования `SmartView`.

При доработке также важно сразу учесть ТЗ:
> После сохранения изменений точка маршрута располагается в списке точек маршрута в порядке, определённом текущей сортировкой (по дате, по длительности или по стоимости) 

> После сохранения точка маршрута располагается в списке точек маршрута в соответствии с датой начала события по этой точке

2022-01-22 08:34 UTC, AlexMasterov approved these changes

2022-01-22 08:34 UTC, AlexMasterov commented on src/presenter/point-presenter.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150630442-d052ad59-4bb9-49ac-936c-79c749fb67e2.png)

</details>

После изменение типа он не соответствует выбранному в списке.

Нужно доработать.

2022-01-22 08:34 UTC, AlexMasterov commented on src/presenter/point-presenter.js
Если изменить стоимость, а потом сменить тип или направление, то стоимость сбрасывается.

См. внимательно ТЗ:
> При смене типа точки маршрута блок с дополнительными опциями перерисовывается, если у нового выбранного типа точки есть опции; или скрывается, если опций нет. **Остальные данные, введённые пользователем, должны быть сохранены**

Нужно доработать.

2022-01-22 08:34 UTC, AlexMasterov commented on src/presenter/point-presenter.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150630671-908abf20-785d-4ae0-8782-81ccf8439ac6.png)
![image](https://user-images.githubusercontent.com/700213/150630677-5b3be3d4-6b30-4326-8009-04c82dd4025f.png)


</details>

После фокуса поля ввода с названием направления остается пустым и форму можно сохранить.

Нужно исправить.

2022-01-22 08:34 UTC, AlexMasterov commented on src/presenter/point-presenter.js
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/150630735-232e0568-0196-4dc2-b29a-97f4efbb53cb.png)
![image](https://user-images.githubusercontent.com/700213/150630739-a772e7a2-29cb-4ee5-99dd-75af4e0949bc.png)


</details>

Изменения в форме не отображаются в списке.

2022-01-22 08:34 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
> +    for (let j = 0; j < datalist.options.length; j++) {
for (let `j` = 0; `j` < datalist.options.length; `j`++) {

Б4
> `i`, j, k, l, t для счётчика в цикле, **`j` для счётчика во вложенном цикле и так далее по алфавиту**

Непонятно, зачем вообще нужен этот цикл 🤔

2022-01-22 08:34 UTC, AlexMasterov commented on src/view/edit-create-point-view.js
> +      evt.target.setCustomValidity('Введите положительное число');
После добавления полю с типом `number` атрибута `min="0"` подобной обработкой занимается сам браузер.

2022-01-22 08:34 UTC, AlexMasterov commented on src/view/point-view.js
>    const {type, destination, price, offers, isFavorite, dateFrom, dateTo, selectedOffers} = point;
```js
selectedOffers // undefined
```
Напомню, что опции в данных точки маршрута `point.offers` уже считаются _выбранными_.

Добавлять еще одно свойство избыточно.

2022-01-22 08:34 UTC, merged