Refactor
htmlacademy-ecmascript/631113-big-trip-16 pull request #16
Opened 2022-02-06 15:11 UTC by 1ak0t

2022-02-06 18:17 UTC, AlexMasterov requested changes

2022-02-06 18:17 UTC, AlexMasterov commented on src/utils/utils.js
>    ,
<details>
<summary>presenter/point-new-presenter.js</summary>

https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/3bdef3cdb2ac0c9954515c5f2c91b718813488ed/src/presenter/point-new-presenter.js#L27
</details>

 this.#editCreatePointComponent.element.`querySelector('.event__reset-btn').textContent = 'Cancel'`;

Прямая работа с элементом компонента нарушает его инкапсуляцию.

Д26
> Операции над DOM-элементами инкапсулированы

2022-02-06 18:17 UTC, AlexMasterov commented on src/utils/utils.js
>    ,
utils/`randomaizer`.js

В ревью задания по созданию "моков" советовал разместить временный код в директории `mock`, чтобы потом удалить всё сразу 😃

Б18
> В коде проекта нет файлов и частей кода, которые не используются, включая закомментированные участки кода

2022-02-06 18:17 UTC, AlexMasterov commented on src/utils/utils.js
>    ,
https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/3bdef3cdb2ac0c9954515c5f2c91b718813488ed/src/model/points-model.js#L104

const adapted`Task` = {...`point`,

🤔

2022-02-06 18:17 UTC, AlexMasterov commented on src/utils/utils.js
>    ,
<details>
<summary>model/points-model.js</summary>

https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/3bdef3cdb2ac0c9954515c5f2c91b718813488ed/src/model/points-model.js#L37-L38
https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/3bdef3cdb2ac0c9954515c5f2c91b718813488ed/src/model/points-model.js#L103-L117
</details>

К данным _опций_ и списку направлений подмешиваются данные точки маршрута со значениями `undefined` 🤔

2022-02-06 18:17 UTC, AlexMasterov commented on src/utils/utils.js
>    ,
https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/3bdef3cdb2ac0c9954515c5f2c91b718813488ed/src/view/list-empty-view.js#L10
https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/3bdef3cdb2ac0c9954515c5f2c91b718813488ed/src/view/loading-view.js#L3

Два компонента создаются один и тот же шаблон, т.е. имеет место дублирование.

Про это писал в замечаниях, предлагая сразу создать один компонент под все сообщения, например, `TripMessage` или `PointMessage`, а само сообщение передавать через аргумент конструктора.

2022-02-07 02:21 UTC, 1ak0t commented on src/utils/utils.js
>    ,
Ты даже как-то удалить смог точки? Я не могу ни удалить, не изменить, ни добавить новую. Постоянно трясется. Только после перезагрузке виден результат этих операций. Что с этим сделать?

2022-02-07 10:21 UTC, AlexMasterov commented on src/utils/utils.js
>    ,
Чтобы с первого раза проверить как можно больше пунктов ТЗ, мне пришлось разобраться и исправить некоторые проблемы в коде. Когда эти проблемы исправишь сам, то сразу сможешь учесть замечания по новым.

> Что с этим сделать?

В первую очередь нужно исправить: https://github.com/htmlacademy-ecmascript/631113-big-trip-16/pull/16#discussion_r800207274.

2022-02-07 12:36 UTC, merged