Module2 task1
htmlacademy-ecmascript/631113-big-trip-16 pull request #4
Opened 2021-12-04 03:42 UTC by 1ak0t

2021-12-04 11:25 UTC, AlexMasterov requested changes

2021-12-04 11:25 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +  const makeOffersList = (offerList) => {
См. задание:
> **Обратите внимание**, дополнительные опции — это отдельная структура данных с типом, к которому опция относится, названием и ценой, а не просто массив строк в структуре точки маршрута

Сейчас нет отдельной структуры со списком доступных предложений:

```
{
  "type": "taxi",
  "offers": [
    {
      "id": 1,
      "title": "Upgrade to a business class",
      "price": 120
    }, {
      "id": 2,
      "title": "Choose the radio station",
      "price": 60
    }
  ]
}
```

<details>
<summary>view/edit-create-event-view.js</summary>

https://github.com/htmlacademy-ecmascript/631113-big-trip-16/blob/fa319ba56de42e16fc6ec94d7639fdb856b2df19/src/view/edit-create-event-view.js#L12-L24
</details>

При редактировании созданной точки маршрута нужно использовать уже _выбранные_ `offers` из данных самой точки и доступные из отдельной структуры. При этом предложения из списка доступных не должны дублировать уже выбранные: _по названию_ и _цене_. Могут быть предложения с одинаковым названием, но с разной (рыночной) ценой.

<details>
<summary>Еще одна проблема</summary>

![image](https://user-images.githubusercontent.com/700213/144707211-6cbb77a9-75aa-46d7-ad34-1af6e95e180c.png)

</details>

Сейчас предложения из точки маршрута даже не отображаются, как _выбранные_. См. макет и ТЗ.

2021-12-04 11:25 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +  const {type, city, price, offers, description, photos} = points;
```
city: "Vienna"
```
В проекте можно выбрать _направление_, которое не обязательно должно быть городом.

Для представления (и хранения) направления используется [структура](https://up.htmlacademy.ru/ecmascript/16/project/big-trip#:~:text=%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85%3A-,Destination,-%3A):

```
{
  "description": "Chamonix, is a beautiful city, a true asian pearl, with crowded streets.",
  "name": "Chamonix",
  "pictures": [
    {
      "src": "http://picsum.photos/300/200?r=0.0762563005163317",
      "description": "Chamonix parliament building"
    }
  ]
}
```
```
description: " Fusce tristique felis at fermentum pharetra"
photos: (2) ['http://picsum.photos/248/152?r=65', 'http://picsum.photos/248/152?r=82']
```

`description` и `photos` — это часть структуры `destination`.

2021-12-04 11:25 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +  const {type, city, price, offers, description, photos} = points;
```
photos: (2) ['http://picsum.photos/248/152?r=67']
```

Структура для фото показана в ТЗ:

```
{
  "src": "http://picsum.photos/300/200?r=0.0762563005163317",
  "description": "Chamonix parliament building"
}
```

Это _объект_, а не _строка_.

2021-12-04 11:25 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +  const {type, city, price, offers, description, photos} = points;
Сейчас в данных точки маршрута нет дат _начала_ и _окончания_ события.

См. в ТЗ [пример JSON-структуры данных с сервера](https://up.htmlacademy.ru/ecmascript/16/project/big-trip#:~:text=in%22%2C%20%22sightseeing%22%2C%20%22restaurant%22%5D-,Point,-%3A):
```
{
  "base_price": 1100,
  "date_from": "2019-07-10T22:55:56.845Z",
  "date_to": "2019-07-11T11:22:13.375Z",
  "destination": $Destination$,
  "id": "0",
  "is_favorite": false,
  "offers": $Array<Offer>$,
  "type": "bus"
}
```

2021-12-04 11:25 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +  const {type, city, price, offers, description, photos} = points;
```
type: "Ship"
```
В данных с сервера значение `type` [хранится в нижнем регистре](https://up.htmlacademy.ru/ecmascript/16/project/big-trip#:~:text=in%22%2C%20%22sightseeing%22%2C%20%22restaurant%22%5D-,Point,-%3A):

```
"type": "bus"
```

2021-12-04 11:25 UTC, AlexMasterov commented on src/view/top-routeinfo-view.js
> +    tripTotalPrice += point.price;
Общая стоимость путешествия должна также включать стоимость всех выбранных предложений.

Прошу сейчас не пытаться выполнить пункты доп. задания, а вместо этого нормально выполнить текущие задание, не нарушая в коде базовые критерии.

2021-12-10 03:47 UTC, 1ak0t commented on src/view/edit-create-event-view.js
> +import {Cities} from '../mock/point.js';
Может я не правильно понимаю, но по заданию:
- Пункт назначения (город). Названия городов можете взять из вёрстки, а можете использовать те, в которых вы хотели бы побывать. Пока это не важно;
- Описание. От 1 до 5 случайных предложений из текста: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras aliquet varius magna, non porta ligula feugiat eget. Fusce tristique felis at fermentum pharetra. Aliquam id orci ut lectus varius viverra. Nullam nunc ex, convallis sed finibus eget, sollicitudin eget ante. Phasellus eros mauris, condimentum sed nibh vitae, sodales efficitur ipsum. Sed blandit, eros vel aliquam faucibus, purus ex euismod diam, eu luctus nunc ante ut dui. Sed sed nisi sed augue convallis suscipit in sed felis. Aliquam erat volutpat. Nunc fermentum tortor ac porta dapibus. In rutrum ac purus sit amet tempus.;
То есть пока не нужно связывать список городов, с их описанием. Да и вроде список городов и destination  никак не связаны, они только для подстановки при создании - редактировании городов. Мы же не будем с сервера тянуть все возможные distination, чтобы из них составить список городов.

2021-12-10 04:06 UTC, 1ak0t commented on src/view/edit-create-event-view.js
> +const createEventEditTemplate = (points) => {
Тут непонятно.
make [meɪk] гл made, made
делать, совершать, сделать, совершить
Получается функции: сделатьСписокГородов, сделатьСписокПредложений, сделатьСписокФото. 
По аналогии с create.

2021-12-10 05:22 UTC, 1ak0t commented on src/view/edit-create-event-view.js
> +  const makeOffersList = (offerList) => {
А это не структура со списком доступных предложений?
const offersByType = {
  'taxi': {
    'offers': [
      {
        'title': 'Upgrade to a business class',
        'price': 100,
      },
      {
        'title': 'Choose radio station',
        'price': 40,
      },
      {
        'title': 'Big luggage',
        'price': 140,
      }
    ]
  },
  'bus': {
    'offers': [
      {
        'title': 'Top floor',
        'price': 30,
      },
      {
        'title': 'Conditioner',
        'price': 20,
      }
    ]
  },
  'train': {
    'offers': [
      {
        'title': 'Speed train',
        'price': 40,
      },
      {
        'title': 'Compartment',
        'price': 100,
      },
      {
        'title': 'Feeding',
        'price': 60,
      }
    ]
  },
  'ship': {
    'offers': []
  },
  'drive': {
    'offers': [
      {
        'title': 'Driver',
        'price': 150,
      },
      {
        'title': 'Elite car',
        'price': 1000,
      },
      {
        'title': 'Conditioner',
        'price': 30,
      },
      {
        'title': 'Cabriolet',
        'price': 220,
      }
    ]
  },
  'flight': {
    'offers': [
      {
        'title': 'Buisness class',
        'price': 200,
      },
      {
        'title': 'First class',
        'price': 800,
      }
    ]
  },
  'check-in': {
    'offers': [
      {
        'title': 'Suite',
        'price': 100,
      },
      {
        'title': 'Family',
        'price': 200,
      },
      {
        'title': 'Apartments ',
        'price': 220,
      },
      {
        'title': 'Executive',
        'price': 350,
      },
      {
        'title': 'President',
        'price': 1300,
      }
    ]
  },
  'sightseeing': {
    'offers': []
  },
  'restaurant': {
    'offers': [
      {
        'title': 'dinner',
        'price': 30,
      }
    ]
  },
};

2021-12-10 05:54 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +  const makeOffersList = (offerList) => {
Сложно читать код без должного форматирования, но это похоже на объект-словарь.

Если из значения ключа убрать промежуточный объект с `offers`, оставив только массив с предложениями, а в каждый объект самого предложения добавить числовое `id`, то такую структуру можно использовать.

См. ТЗ:
> GET /offers

> **Response**:
> `Body`: _массив_ из элементов вида `Offer`

В этом случае массив с предложениями с сервера потребуется преобразовать в такой объект-словарь.

2021-12-10 06:02 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +import {Cities} from '../mock/point.js';
Из-за подобной формулировки задания это замечание сейчас указано как необязательное к исправлению 😃

> Мы же не будем с сервера тянуть все возможные distination, чтобы из них составить список городов

См. ТЗ:

> Пункт назначения. **Выбирается из списка предложенных значений, полученных с сервера.** Пользователь не может ввести свой вариант для пункта назначения

> **Пункты назначения /destinations**
> GET /destinations

> **Response**
> `Body`: массив из элементов вида `Destination`

`Destination`
```json
{
  "description": "Chamonix, is a beautiful city, a true asian pearl, with crowded streets.",
  "name": "Chamonix",
  "pictures": [
    {
      "src": "http://picsum.photos/300/200?r=0.0762563005163317",
      "description": "Chamonix parliament building"
    }
  ]
}
```
Список предложений формируется по значению каждого объекта `Destination.name` из массива `destinations`.

2021-12-10 06:11 UTC, 1ak0t commented on src/view/edit-create-event-view.js
> +import {Cities} from '../mock/point.js';
А не рациональней подтянуть сначала список направлений, и при его выборе уже делать запрос на сервер за нужной структурой destination, чтобы сразу все не тянуть?

2021-12-10 06:12 UTC, 1ak0t commented on src/view/edit-create-event-view.js
> +import {Cities} from '../mock/point.js';
Это так, интересно просто)

2021-12-10 06:31 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +import {Cities} from '../mock/point.js';
Этот вопрос следует задать авторам курса.

По ТЗ структура для данных точки маршрута хранит копию `Destination`, которая выбирается из общего списка. То же самое с `offers`, которые в этом структуре считаются выбранными (для типа точки маршрута) из общего списка `Offers`.

Подобное дублирование позволяет отложить получение списка доступных пунктов назначений и предложений до открытия формы редактирования или создания новой. Но **это по желанию**, а в простом случае они запрашиваются при старте приложения.

> А не рациональней подтянуть сначала список направлений, и **при его выборе уже делать запрос на сервер за нужной структурой destination**, чтобы сразу все не тянуть?

Текущий сервер подобного не умеют, и вряд ли его такому научат: делать на каждый выбор направления сетевой запрос, чтобы получить к нему описание и фото — это что-то вроде [антипаттерна](https://ru.wikipedia.org/wiki/%D0%90%D0%BD%D1%82%D0%B8%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD) для REST-подобного API 😄

2021-12-10 07:03 UTC, AlexMasterov commented on src/view/edit-create-event-view.js
> +const createEventEditTemplate = (points) => {
Для критерия будет достаточно указать, что создается шаблон (= `Template`).

2021-12-10 10:02 UTC, AlexMasterov requested changes
Пожалуйста, постарайся доработать и исправить код по открытым замечаниям.

Остальное сейчас достаточно учесть, а доработать можно позже.

2021-12-15 11:58 UTC, 1ak0t commented on src/view/event-view.js
> +  const createOfferListTemplate = (offerList) => {
Что из этого тип данных?

2021-12-15 12:05 UTC, 1ak0t commented on src/view/event-view.js
> +    } else {
если будет пустой offers, чтобы не вернула undefined

2021-12-15 12:10 UTC, AlexMasterov commented on src/view/event-view.js
> +  const createOfferListTemplate = (offerList) => {
> Что из этого тип данных?

`list`, т.е. список.

Для именования _встроенного_ списка (массива) достаточно использовать множественное число.

> Если использовать стороннею реализацию списка, то `List` в название имеет смысл

2021-12-15 12:12 UTC, 1ak0t commented on src/view/event-view.js
> +  const isLike = isFavorite ? 'event__favorite-btn  event__favorite-btn--active' : 'event__favorite-btn';
также называли в лайве. Странно(

2021-12-15 12:13 UTC, 1ak0t commented on src/view/event-view.js
> +      return offerListFragment.filter(() => getRandomNumberInt(0,1)).join('');
Но сейчас как то же надо случайными данными заполнить. О чем и говорили в лайве. Что бы было похоже на реальные (разные) данные

2021-12-15 12:16 UTC, AlexMasterov commented on src/view/event-view.js
> +    } else {
> если будет пустой offers, чтобы не вернула undefined

Проблема не в `return`, а в `else`, который избыточен.

См. [пояснение критерия Д12 на прошлом JS1-24](https://up.htmlacademy.ru/javascript/24/module/2/live) (~20:48).

> [Не используй `else`](https://www.youtube.com/watch?v=bn10mUjnwEc#t=12m36s), когда это возможно

2021-12-15 12:24 UTC, AlexMasterov commented on src/view/event-view.js
> +  const isLike = isFavorite ? 'event__favorite-btn  event__favorite-btn--active' : 'event__favorite-btn';
> **также называли в лайве**. Странно(

Можно ссылку?

См. [пример в демо проекте](https://github.com/htmlacademy-ecmascript/taskmanager-16/blob/module-5/src/view/task-view.js#L9-L11):

```js
const repeatClassName = isTaskRepeating(repeating)
  ? 'card--repeat'
  : '';
```
[`isTaskRepeating`](https://github.com/htmlacademy-ecmascript/taskmanager-16/blob/39997ddf12aa5d9f9a7d5365913354380b82cf60/src/utils/task.js#L7) — с `is`, это функция-предикат, которая возвращает булево значение:

```js
const isTaskRepeating = (repeating) => Object.values(repeating).some(Boolean);
```

2021-12-15 12:24 UTC, 1ak0t commented on src/utils/utils.js
> +const makePhotosListTemplate = (photos) => {
В задании - Фотографии (одна или несколько).
Исходил из этого.
(если в предложениях было указано 0-5, там предусмотрел)

2021-12-15 12:30 UTC, AlexMasterov commented on src/view/event-view.js
> +      return offerListFragment.filter(() => getRandomNumberInt(0,1)).join('');
> Но сейчас как то же надо случайными данными заполнить. О чем и говорили в лайве. Что бы было похоже на реальные (разные) данные

См. [ответ авторов курса](https://up.htmlacademy.ru/ecmascript/16/module/2/questions#:~:text=%D0%A2%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE%20%D1%81%D0%B3%D0%B5%D0%BD%D0%B5%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5%20%22%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B0%D1%81%D1%82%D0%BE%D1%8F%D1%89%D0%B8%D0%B5%22%20%D0%B8%20%D0%BD%D0%B0%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D1%8B%20%D0%B8%D1%85%20%D0%BF%D1%80%D0%B8%D0%BD%D0%B8%D0%BC%D0%B0%D1%82%D1%8C.):
> Только сгенерировать данные "как настоящие" и научить шаблоны их принимать.

2021-12-15 12:30 UTC, 1ak0t commented on src/view/event-view.js
> +  const createOfferListTemplate = (offerList) => {
https://developer.mozilla.org/ru/docs/Web/JavaScript/Data_structures

Вроде нет такого типа данных

2021-12-15 12:37 UTC, AlexMasterov commented on src/view/event-view.js
> +      return offerListFragment.filter(() => getRandomNumberInt(0,1)).join('');
При редактировании созданной точки маршрута нужно использовать уже выбранные `offers` из данных самой точки и доступные из отдельной структуры. При этом предложения из общего списка не должны дублировать уже выбранные: по названию и цене. Могут быть предложения с одинаковым названием, но с разной (рыночной) ценой.

> На этом интенсиве у предложений них появились `id`, который позволяет упростить по устранения дублирования

Тип из данных точки маршрута нужно использовать для поисках доступных предложений, которые хранятся в отдельной структуре. Пример структуры показан в ТЗ, но можно придумать свою, например, использовать словарь вместо массива.

2021-12-15 12:38 UTC, AlexMasterov commented on src/view/event-view.js
> +      return offerListFragment.filter(() => getRandomNumberInt(0,1)).join('');
> При редактировании созданной точки маршрута нужно использовать уже выбранные `offers` из данных самой точки и доступные из отдельной структуры. При этом предложения из общего списка не должны дублировать уже выбранные: по названию и цене. Могут быть предложения с одинаковым названием, но с разной (рыночной) ценой.
> 
> > На этом интенсиве у предложений них появились `id`, который позволяет упростить по устранения дублирования
> 
> Тип из данных точки маршрута нужно использовать для поисках доступных предложений, которые хранятся в отдельной структуре. Пример структуры показан в ТЗ, но можно придумать свою, например, использовать словарь вместо массива.

Ничего из этого не реализовано, сейчас даже предложения в `point.offers` не отображаются как выбранные.

2021-12-15 12:42 UTC, AlexMasterov commented on src/view/event-view.js
> +      return offerListFragment.filter(() => getRandomNumberInt(0,1)).join('');
> Но сейчас как то же надо случайными данными заполнить

Заполнить, чтобы все след. задания просто видеть, как меняется кол. предложений, а при получение реальных данных с сервера всё переделывать? 😃

К сожалению, подобные тест. данные (в отсутствие данных с сервера) не помогают реализовать логику ТЗ, они даже отображаются неправильно. Они позволяют лишь _формально_ закрыть текущие задание.

2021-12-15 12:44 UTC, AlexMasterov commented on src/view/event-view.js
> +      return offerListFragment.filter(() => getRandomNumberInt(0,1)).join('');
Текущие замечание указано как скрытое с пометкой `abuse`, что в моем ревью означает его необязательное выполнение в этом задание. Достаточно просто иметь в виду.

2021-12-15 12:50 UTC, AlexMasterov commented on src/view/event-view.js
> +  const createOfferListTemplate = (offerList) => {
> https://developer.mozilla.org/ru/docs/Web/JavaScript/Data_structures
> 
> Вроде нет такого типа данных

Для критерия Б9 использую `typeof`, который показывает специфицированные типы в языке, а не абстрактные. Но на защите проекта его могут применять к названиям `list` и `array`. В этом случае придаться тратить время, чтобы парировать 😃

В моем замечание важно учесть Б8, а Б9 нужен, чтобы при исправление не были добавлены этим самые `lists` и `arrays`, т.е. такое же масло масленое, которое станет проблемой на защите.

2021-12-15 12:51 UTC, AlexMasterov commented on src/view/event-view.js
> +  const createOfferListTemplate = (offerList) => {
`offerList` достаточно пока просто исправить на `offers`.

`offerListFragment` вообще не нужен. Лучше просто используй `.map` + `.join`, без создания переменной с массивом.

2021-12-15 12:57 UTC, AlexMasterov commented on src/utils/utils.js
> +const makePhotosListTemplate = (photos) => {
Тут проблема в реализации функции. 

Сейчас функция может вернуть значения разного типа: `string` и `undefined`. Это уже плохой дизайн. Если массив пустой, то следует вернуть пустую строку. 

Еще лучше подобные проверки делать на уровне выше, чтобы в случае пустого массива функцию вообще не вызывать.

2021-12-15 13:01 UTC, AlexMasterov commented
👍🏻

@1ak0t, благодарю за уточняющие вопросы по замечаниям.

2021-12-15 13:01 UTC, merged