Lesson 5.1
htmlacademy-ecmascript/631113-big-trip-16 pull request #8
Opened 2022-01-07 15:36 UTC by 1ak0t

2022-01-07 15:41 UTC, 1ak0t commented
Только так и не понял, почему когда ставишь лайк - перерисовываются фичи. Остальное не меняется.

2022-01-07 16:06 UTC, AlexMasterov requested changes

2022-01-07 16:06 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +  #EscKeyPressHandler = (evt) => {
Если закрыть форму редактирования нажатием на `Esc`, то перестает работать кнопка `.event__rollup-btn` на повторное открытие.

Нужно разобраться и исправить.

2022-01-07 16:07 UTC, AlexMasterov commented
> Только так и не понял, почему когда ставишь лайк - перерисовываются фичи. Остальное не меняется.

См. https://github.com/htmlacademy-ecmascript/631113-big-trip-16/pull/4#discussion_r766523479.

2022-01-12 13:30 UTC, AlexMasterov approved these changes

2022-01-12 13:30 UTC, AlexMasterov commented on src/view/point-view.js
>      const offerListFragment = [];
const `offerListFragment` = [];

Б8
> Массивы названы существительными во множественном числе

См. https://github.com/htmlacademy-ecmascript/631113-big-trip-16/pull/4#discussion_r766519106.

2022-01-12 13:30 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/149146936-b20cb1c8-e0a4-4265-8946-cdc54418f280.png)

</details>
<details>
<summary>Ожидание (markup/edit-point.html)</summary>

![image](https://user-images.githubusercontent.com/700213/149147000-5ffc63c4-3141-4e62-8359-998ea86ac37b.png)

</details>

См. ТЗ:
> Дополнительная опция применяется к точке маршрута один раз. Повторный клик на дополнительную опцию отменяет её применение

> В зависимости от состояния, некоторым элементам управления применяются соответствующие классы оформления. Например, активный фильтр и так далее. Примеры доступны в директории с вёрсткой (markup)

Сейчас выбранные опции отображаются как невыбранные, т.е. без атрибута `checked`.

> Напомню, что в данных точки маршрута `point.offers` _все_ опции считаются выбранными. Все доступные опции хранятся в отдельной структуре, которую потребуется получить с сервера отдельно. Невыбранные опции из этой структуре потребуется "смешать" с выбранными из данных точки маршрута, исключая дубликаты по `id`

Нужно доработать.

2022-01-12 13:30 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +
См. ТЗ:

> Если пользователь внёс изменения в точку маршрута, не выполнил сохранение и пытается перейти к редактированию другой точки маршрута либо создать новую, то в этом случае открытая **форма редактирования скрывается без сохранения изменений**

Сейчас если открыть форму редактирования точки маршрута и кликнуть на опцию, то закрыв форму _без сохранения по кнопке `Save`, она окажется выбранной и отобразиться в списке у точки маршрута.

Нужно исправить.

> \+ непонятно, зачем при клике не поле опции перерисовывать форму, тем более всю, ведь браузер сам добавит атрибут `checked` и применит стили (= действие по умолчанию)

2022-01-12 13:30 UTC, AlexMasterov commented on src/presenter/point-presenter.js
> +
<details>
<summary>Проблема</summary>

![image](https://user-images.githubusercontent.com/700213/149149145-97fe634a-ab6a-4f3a-9804-439e81dd4a0b.png)

</details>

Сейчас если у пункта назначения нет описания **и** фото, то блок `DESTINATION` отображается.

См. ТЗ:
> При смене пункта назначения блок с описанием <...> скрывается, если у пункта назначения нет описания **и** фотографий к нему

Нужно доработать.

2022-01-12 13:30 UTC, merged